version: '3'
services:
  app:
    image: control-panel:1.0.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    container_name: controlpanel
    restart: "no"