version: '3'
services:
  pythonscript:
    image: sns/pythongpt:2.00
    environment: #another option is whatToRun=comments or price
      - token=Z8PIzBNZcT7cpgvJusDBVTaWXd1tzo9RJin2O2OQpaOOBzOEO9TAClGjPXR_IpmMHtqr4fAeUeOQklKyLdtsNw==
    container_name: pythonscriptgpt2
    restart: "no"
